### ISSUE TITLE
Validate TAB when Custom Select Tag

### ISSUE THREAD

**Issue by rafaelcdelgado** [Grupo-AFAL/frontend-helpers#18]
When you are typing sometimes you want to type "TAB" in order to go to the next input, well, right now is not allowing, automatically assign the next "LI" on the "UL". 

We need to verify if there is nothing on the FakeInput, ignore the AddSelected and behavioral as normal to the next HTML Element.

**Comment by fedegl** [comment]
@alexisKinto Esto ya esta en produccion? Lo podemos cerrar?

**Comment by alexisKinto** [comment]
> @alexisKinto Esto ya esta en produccion? Lo podemos cerrar?

Creo que falta actualizar la version de FH que esta utilizando GA apps en producción.
(En la branch que estoy trabajando(de GA apps) ya tiene la ultima version de Frontend H., cuando haga merge se deberían ver los cambios)
