### ISSUE TITLE
Error on TagsInput

### ISSUE THREAD

**Issue by rafaelcdelgado** [Grupo-AFAL/frontend-helpers#8]
When press "Backspace" an there is no tag added yet.

Unhandled Runtime Error
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/78398979/110880216-1f306200-8293-11eb-8637-962598df6542.png">

https://github.com/Grupo-AFAL/frontend-helpers/blob/9668000dff140f252a0e9dd19556b58a34327c3b/javascript/src/controllers/tags-controller.js#L57

**Comment by fedegl** [comment]
Has been fixed with this PR: https://github.com/Grupo-AFAL/frontend-helpers/pull/12
